title: Ronnen Nagal
author: Ronnen Nagal
email: nagalr@me.com
description: Data Scientist experienced in executing data-driven solutions, including assessing box office revenue, digitizing records and building long-lasting relationships across hedge-funds and consultancy companies. 
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: @nagalr
github_username:  nagalr
facebook_username: 

# Build settings
markdown: kramdown
#theme: jekyll-theme-clean-blog
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
