title: Ronnen Nagal
author: Ronnen Nagal
email: nagalr@me.com
description:
Some changes
  Data Scientist experienced in executing data-driven solutions, including assessing box office revenue, digitizing records and building long-lasting relationships across hedge-funds and consultancy companies. 
SNN Local News 6 is the only television source for local news on demand, with local weather every fifteen minutes. In addition to providing viewers with the local news of the day and immediate, breaking news, SNN management has, as part of the station’s mission, placed the highest priority on serving our local arts and charitable organizations through significant news coverage opportunities and in-kind advertising support, as well as ongoing involvement in or telecast of a wide array of area events, special programs and projects.
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
facebook_username: ron

# Build settings
markdown: kramdown
#theme: jekyll-theme-clean-blog
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
