title: Ronnen Nagal
author: Ronnen Nagal
email: nagalr@gmail.com
description: Software Developer
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nagalr
github_username: nagalr
facebook_username: 
linkedin_username: ronnen

# Build settings
markdown: kramdown
#theme: jekyll-theme-clean-blog
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
